const APP_VERSION='7.3.0';
const STORAGE_KEY='sporTotoStateV711';
const SUPABASE_URL='https://ffnggyshacjwcdbwsazd.supabase.co';
const SUPABASE_KEY='sb_publishable_oVFfgUEbWsQbpoLF1ftRLw_NOUwrKH4';
const LIVE_DURATION_MINUTES=120;
const state={matchNames:[],matchLeagues:Array(15).fill(''),matchDates:Array(15).fill(''),matchTimes:Array(15).fill(''),results:Array(15).fill(''),columns:[],weekName:'Güncel Hafta',fileName:'',weekKey:'',cloudId:null,cloudUpdatedAt:null};
let db=null,currentUser=null,realtimeChannel=null,cloudWeeks=[],saveTimer=null,isApplyingRemote=false,currentCategory=15,currentCategoryRows={15:[],14:[],13:[],12:[],11:[]},sheetMode='category';
const $=id=>document.getElementById(id);
const trUpper=v=>String(v??'').trim().toLocaleUpperCase('tr-TR');
function normalize(v){const s=trUpper(v);return s==='1'||s==='2'||s==='X'?s:''}
function cleanName(v,i){const s=String(v??'').trim();return s||`Maç ${i+1}`}
function safeStatePayload(){return {matchNames:state.matchNames,matchLeagues:state.matchLeagues,matchDates:state.matchDates,matchTimes:state.matchTimes,results:state.results,columns:state.columns,weekName:state.weekName,fileName:state.fileName,weekKey:state.weekKey}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s&&Array.isArray(s.columns)){Object.assign(state,s);return}}catch(e){}Object.assign(state,window.INITIAL_DATA||{});state.results=Array(15).fill('');saveLocal()}
function slug(v){return String(v||'hafta').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'hafta'}
function makeWeekKey(imported){const firstDate=(imported.matchDates||[]).find(Boolean)||'';return slug(`${imported.weekName}-${firstDate}`)}
function setSync(text,kind='offline'){const b=$('syncBadge');b.textContent=text;b.className=`sync-badge ${kind}`}
function updateHeader(){
  $('weekName').textContent=state.weekName||state.fileName||'Güncel Hafta';
  $('fileSummary').textContent=state.fileName||'Henüz dosya seçilmedi';
  $('uploadInfo').textContent=state.fileName?`${state.columns.length.toLocaleString('tr-TR')} kolon • ${(state.columns.length*10).toLocaleString('tr-TR')} TL`:'Excel\'deki takım adları, tarih, saat ve kolonlar okunur.';
  $('versionBadge').textContent='v'+APP_VERSION;
}
function normalizeState(){state.matchNames=(state.matchNames||[]).slice(0,15);while(state.matchNames.length<15)state.matchNames.push('Maç '+(state.matchNames.length+1));state.matchLeagues=(state.matchLeagues||[]).map(v=>String(v??'').trim()).slice(0,15);while(state.matchLeagues.length<15)state.matchLeagues.push('');state.matchDates=(state.matchDates||[]).map(v=>String(v??'').trim()).slice(0,15);while(state.matchDates.length<15)state.matchDates.push('');state.matchTimes=(state.matchTimes||[]).map(v=>String(v??'').trim()).slice(0,15);while(state.matchTimes.length<15)state.matchTimes.push('');state.results=(state.results||[]).map(normalize).slice(0,15);while(state.results.length<15)state.results.push('');state.columns=(state.columns||[]).filter(c=>Array.isArray(c)&&c.length===15).map(c=>c.map(normalize));}
function parseMatchDateTime(dateValue,timeValue){const date=String(dateValue||'').trim(),time=String(timeValue||'').trim();if(!date||!time)return null;let y,m,d,hit=date.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(hit){d=+hit[1];m=+hit[2];y=+hit[3]}else if((hit=date.match(/^(\d{4})[.\/-](\d{1,2})[.\/-](\d{1,2})$/))){y=+hit[1];m=+hit[2];d=+hit[3]}else return null;const clock=time.match(/^(\d{1,2})[:.](\d{2})/);if(!clock)return null;const hh=+clock[1],mm=+clock[2];if(hh>23||mm>59)return null;const dt=new Date(y,m-1,d,hh,mm);return Number.isNaN(dt.getTime())?null:dt}
function getMatchStatus(dateValue,timeValue,now=new Date()){const start=parseMatchDateTime(dateValue,timeValue);if(!start)return null;const diff=start-now;if(diff>0){const mins=Math.ceil(diff/60000),days=Math.floor(mins/1440),hours=Math.floor((mins%1440)/60),minutes=mins%60;const text=days>0?`${days} gün ${hours} saat kaldı`:hours>0?`${hours} saat ${minutes} dk kaldı`:`${Math.max(1,minutes)} dk kaldı`;return{kind:'upcoming',label:'Başlamadı',text:`⏳ ${text}`}}if(diff>=-(LIVE_DURATION_MINUTES*60000))return{kind:'live',label:'Canlı',text:'● Maç oynanıyor'};return{kind:'finished',label:'Tamamlandı',text:'Maç tamamlandı'}}
function matchStatusHtml(i){const s=getMatchStatus(state.matchDates[i],state.matchTimes[i]);return s?`<div class="match-status ${s.kind}"><span class="status-label">${s.label}</span><span class="status-text">${s.text}</span></div>`:''}
function refreshMatchStatuses(){document.querySelectorAll('.match[data-match-index]').forEach(card=>{const i=Number(card.dataset.matchIndex),slot=card.querySelector('.match-status-slot'),status=getMatchStatus(state.matchDates[i],state.matchTimes[i]);if(slot)slot.innerHTML=status?matchStatusHtml(i):'';const finished=status?.kind==='finished';card.classList.toggle('match-finished',finished)})}
function getPickDistribution(matchIndex){const counts={'1':0,'X':0,'2':0};for(const col of state.columns){const pick=col?.[matchIndex];if(pick in counts)counts[pick]++}const total=counts['1']+counts.X+counts['2'];return {counts,total}}
function renderMatches(){const box=$('matches');box.innerHTML='';state.matchNames.forEach((name,i)=>{const d=document.createElement('div'),status=getMatchStatus(state.matchDates[i],state.matchTimes[i]),finished=status?.kind==='finished';d.className=`match${finished?' match-finished':''}`;d.dataset.matchIndex=i;const league=String(state.matchLeagues[i]||'').trim(),date=String(state.matchDates[i]||'').trim(),time=String(state.matchTimes[i]||'').trim();const leagueHtml=league?`<div class="match-league">${league}</div>`:'';const meta=(date||time)?`<div class="match-meta">${date?`<span><b class="meta-icon">▣</b>${date}</span>`:''}${time?`<span><b class="meta-icon clock">◷</b>${time}</span>`:''}</div>`:'';const distribution=getPickDistribution(i);d.innerHTML=`<div class="match-head"><span class="match-no">${i+1}</span><div class="match-info"><span class="match-name">${name||'Maç '+(i+1)}</span>${leagueHtml}${meta}<div class="match-status-slot">${matchStatusHtml(i)}</div></div></div>${distribution.total?`<div class="distribution-title">${distribution.total.toLocaleString('tr-TR')} kolonda seçim dağılımı</div>`:''}<div class="choices">${['1','X','2'].map(v=>{const count=distribution.counts[v],percent=distribution.total?Math.round(count/distribution.total*100):0;return `<button class="choice ${state.results[i]===v?'active':''}" data-i="${i}" data-v="${v}"><span class="choice-value">${v}</span>${distribution.total?`<small class="choice-count">${count.toLocaleString('tr-TR')} kolon</small><small class="choice-percent">%${percent}</small>`:''}</button>`}).join('')}</div>`;box.appendChild(d)});box.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,v=b.dataset.v;state.results[i]=state.results[i]===v?'':v;saveLocal();renderMatches();calculate();queueCloudSave()})}
function calculate(){let counts={15:0,14:0,13:0,12:0,11:0};currentCategoryRows={15:[],14:[],13:[],12:[],11:[]};const entered=state.results.filter(Boolean).length;for(let idx=0;idx<state.columns.length;idx++){const col=state.columns[idx];let wrong=0;for(let i=0;i<15;i++)if(state.results[i]&&col[i]!==state.results[i])wrong++;const score=15-wrong;const category=score>=15?15:score===14?14:score===13?13:score===12?12:11;counts[category]++;currentCategoryRows[category].push([idx+1,col,wrong])}$('total').textContent=state.columns.length.toLocaleString('tr-TR');$('cost').textContent=(state.columns.length*10).toLocaleString('tr-TR')+' TL';$('s15').textContent=counts[15].toLocaleString('tr-TR');$('s14').textContent=counts[14].toLocaleString('tr-TR');$('s13').textContent=counts[13].toLocaleString('tr-TR');$('s12').textContent=counts[12].toLocaleString('tr-TR');$('s11').textContent=counts[11].toLocaleString('tr-TR');$('remaining').textContent=15-entered;const percent=Math.round((entered/15)*100);$('progressText').textContent=`${entered} / 15 maç tamamlandı`;$('progressPercent').textContent=`%${percent}`;$('progressBar').style.width=`${percent}%`;const total=counts[15]+counts[14]+counts[13]+counts[12]+counts[11];$('statsSource').textContent=total===state.columns.length?`${entered} maç seçildi • Kategoriler toplamı: ${total.toLocaleString('tr-TR')} kolon`:`Hesap kontrolü başarısız: ${total}/${state.columns.length}`;if(document.body.classList.contains('sheet-open'))renderOpenSheet()}
function categoryTitle(category){return category===11?'11 ve Altı':`${category} Devam`}
function renderCategorySheet(){const rows=currentCategoryRows[currentCategory]||[];$('sheetTitle').textContent=`${categoryTitle(currentCategory)} Kolonları`;$('sheetCount').textContent=`${rows.length.toLocaleString('tr-TR')} kolon`;const empty=$('sheetEmpty'),list=$('survivorsList');if(!rows.length){list.innerHTML='';empty.classList.remove('hidden');empty.innerHTML=`<strong>${categoryTitle(currentCategory)} kolonu yok</strong>Yeni sonuç seçildikçe bu liste otomatik güncellenir.`;return}empty.classList.add('hidden');const pending=state.results.filter(v=>!v).length;list.innerHTML=rows.map(([n,c,wrong])=>`<article class="column-card"><div class="column-card-head"><div><span class="column-number">Kolon #${n}</span><small class="column-status"><span class="error-count">${wrong} hata</span><span class="pending-count">${pending} bekliyor</span></small></div><button class="copy-column" data-column="${c.join('-')}">Kopyala</button></div><div class="column-picks">${c.map((v,i)=>{const cls=!state.results[i]?'pending-pick':state.results[i]!==v?'wrong-pick':'correct-pick';return `<span class="column-pick ${cls}" title="${!state.results[i]?'Sonuç bekleniyor':state.results[i]===v?'Doğru tahmin':'Yanlış tahmin'}">${v}</span>`}).join('')}</div></article>`).join('');list.querySelectorAll('.copy-column').forEach(btn=>btn.onclick=async()=>{try{await navigator.clipboard.writeText(btn.dataset.column);btn.textContent='Kopyalandı';btn.classList.add('copied');setTimeout(()=>{btn.textContent='Kopyala';btn.classList.remove('copied')},1000)}catch(e){alert(btn.dataset.column)}})}
function renderRemainingMatchesSheet(){const pending=state.results.map((v,i)=>!v?i:-1).filter(i=>i>=0);$('sheetTitle').textContent='Kalan Maçlar';$('sheetCount').textContent=`${pending.length} maç`;const empty=$('sheetEmpty'),list=$('survivorsList');if(!pending.length){list.innerHTML='';empty.classList.remove('hidden');empty.innerHTML='<strong>Tüm maçlar tamamlandı</strong>Girilmeyi bekleyen maç sonucu bulunmuyor.';return}empty.classList.add('hidden');list.innerHTML=pending.map(i=>{const date=String(state.matchDates[i]||'').trim(),time=String(state.matchTimes[i]||'').trim(),status=getMatchStatus(date,time);const league=String(state.matchLeagues[i]||'').trim();return `<article class="remaining-match-card"><span class="remaining-match-no">${i+1}</span><div class="remaining-match-info"><strong>${state.matchNames[i]||`Maç ${i+1}`}</strong>${league?`<div class="remaining-league">${league}</div>`:''}<p>${date?`📅 ${date}`:''}${date&&time?' • ':''}${time?`🕒 ${time}`:''}</p>${status?`<small class="remaining-status ${status.kind}">${status.label} • ${status.text}</small>`:'<small class="remaining-status upcoming">Sonuç bekleniyor</small>'}</div></article>`}).join('')}
function renderOpenSheet(){if(sheetMode==='remaining')renderRemainingMatchesSheet();else renderCategorySheet()}
function openCategory(category){sheetMode='category';currentCategory=Number(category)||15;renderCategorySheet();$('survivorsSheet').classList.remove('hidden');$('sheetBackdrop').classList.remove('hidden');document.body.classList.add('sheet-open')}
function openRemainingMatches(){sheetMode='remaining';renderRemainingMatchesSheet();$('survivorsSheet').classList.remove('hidden');$('sheetBackdrop').classList.remove('hidden');document.body.classList.add('sheet-open')}
function closeSurvivors(){$('survivorsSheet').classList.add('hidden');$('sheetBackdrop').classList.add('hidden');document.body.classList.remove('sheet-open')}
function parseRows(rows){const out=[];if(!Array.isArray(rows)||!rows.length)return out;let pickIndexes=null;for(const row of rows.slice(0,20)){const upper=(row||[]).map(trUpper),indexes=[];for(let n=1;n<=15;n++){const idx=upper.findIndex(v=>[`M${n}`,`MAÇ ${n}`,`MAC ${n}`].includes(v));if(idx<0){indexes.length=0;break}indexes.push(idx)}if(indexes.length===15){pickIndexes=indexes;break}}for(const row of rows){let vals;if(pickIndexes)vals=pickIndexes.map(i=>normalize((row||[])[i]));else{const raw=row||[],afterId=raw.slice(1,16).map(normalize);if(raw.length>=16&&afterId.every(Boolean))vals=afterId;else{vals=[];for(let start=0;start<=raw.length-15;start++){const c=raw.slice(start,start+15).map(normalize);if(c.every(Boolean)){vals=c;break}}}}if(vals&&vals.length===15&&vals.every(Boolean))out.push(vals)}return out}
function rowLabelIndex(rows,labels){const wanted=labels.map(trUpper);for(let r=0;r<rows.length;r++)for(let c=0;c<Math.min(4,(rows[r]||[]).length);c++)if(wanted.includes(trUpper(rows[r][c])))return{r,c};return null}
function extractMatchData(rows){const nameHit=rowLabelIndex(rows,['Maç Adı','Mac Adi','Maçlar','Takımlar']),leagueHit=rowLabelIndex(rows,['Lig','Ligler','Lig Adı','Lig Adi']),dateHit=rowLabelIndex(rows,['Tarih','Tarihler','Maç Tarihi','Mac Tarihi']),timeHit=rowLabelIndex(rows,['Saat','Saatler','Maç Saati','Mac Saati']);let matchNames=null,matchLeagues=Array(15).fill(''),matchDates=Array(15).fill(''),matchTimes=Array(15).fill('');if(nameHit)matchNames=(rows[nameHit.r]||[]).slice(nameHit.c+1,nameHit.c+16).map((v,i)=>cleanName(v,i));if(leagueHit)matchLeagues=(rows[leagueHit.r]||[]).slice(leagueHit.c+1,leagueHit.c+16).map(v=>String(v??'').trim());if(dateHit)matchDates=(rows[dateHit.r]||[]).slice(dateHit.c+1,dateHit.c+16).map(v=>String(v??'').trim());if(timeHit)matchTimes=(rows[timeHit.r]||[]).slice(timeHit.c+1,timeHit.c+16).map(v=>String(v??'').trim());return{matchNames:matchNames||Array.from({length:15},(_,i)=>`Maç ${i+1}`),matchLeagues,matchDates,matchTimes}}
function parseWorkbook(wb,fileName){const panelName=wb.SheetNames.find(n=>trUpper(n)==='TAKİP PANELİ')||wb.SheetNames[0],panelRows=XLSX.utils.sheet_to_json(wb.Sheets[panelName],{header:1,raw:false,defval:'',blankrows:false}),{matchNames,matchLeagues,matchDates,matchTimes}=extractMatchData(panelRows);let colName=wb.SheetNames.find(n=>trUpper(n)==='KOLONLAR');if(!colName)colName=wb.SheetNames.find(n=>n!==panelName)||panelName;const columns=parseRows(XLSX.utils.sheet_to_json(wb.Sheets[colName],{header:1,raw:false,defval:'',blankrows:false}));if(!columns.length)throw new Error('Kolonlar sayfasında 15 sonuçtan oluşan kolon bulunamadı.');const weekName=fileName.replace(/\.(xlsx|xls|csv|txt)$/i,'').replace(/[_-]+/g,' ').trim();const imported={matchNames,matchLeagues,matchDates,matchTimes,results:Array(15).fill(''),columns,weekName,fileName};imported.weekKey=makeWeekKey(imported);return imported}
async function initSupabase(){if(!window.supabase){setSync('Bulut yüklenemedi','error');return}db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const {data:{session}}=await db.auth.getSession();await handleSession(session);db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>handleSession(session),0))}
async function handleSession(session){currentUser=session?.user||null;if(!currentUser){unsubscribeRealtime();$('cloudBar').classList.add('hidden');setSync('Giriş gerekli','offline');return}$('cloudBar').classList.remove('hidden');$('cloudUser').textContent=currentUser.email||'Karum Toto hesabı';setSync('Bağlandı','online');closeAuth();await loadCloudWeeks();subscribeRealtime()}
function showAuth(){const logged=!!currentUser;$('authModal').classList.remove('hidden');$('authBackdrop').classList.remove('hidden');$('logoutBtn').classList.toggle('hidden',!logged);$('loginBtn').classList.toggle('hidden',logged);$('signupBtn').classList.toggle('hidden',logged);$('authEmail').value=currentUser?.email||'';$('authMessage').textContent=logged?'Bu hesapla bulut senkronizasyonu açık.':''}
function closeAuth(){$('authModal').classList.add('hidden');$('authBackdrop').classList.add('hidden')}
function authMessage(text,bad=false){const el=$('authMessage');el.textContent=text;el.className='auth-message '+(bad?'bad':'ok')}
async function login(){try{authMessage('Giriş yapılıyor...');const {error}=await db.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error)throw error;authMessage('Giriş başarılı.')}catch(e){authMessage(e.message,true)}}
async function signup(){try{authMessage('Hesap oluşturuluyor...');const {data,error}=await db.auth.signUp({email:$('authEmail').value.trim(),password:$('authPassword').value});if(error)throw error;authMessage(data.session?'Hesap oluşturuldu ve giriş yapıldı.':'Hesap oluşturuldu. E-postandaki onay bağlantısına basıp giriş yap.')}catch(e){authMessage(e.message,true)}}
async function logout(){await db.auth.signOut();cloudWeeks=[];$('weekSelect').innerHTML='<option value="">Hafta seç</option>';authMessage('Çıkış yapıldı.');closeAuth()}
async function loadCloudWeeks(){if(!currentUser)return;const {data,error}=await db.from('karum_weeks').select('id,week_key,week_name,file_name,payload,updated_at').order('updated_at',{ascending:false});if(error){setSync('Tablo kurulmalı','error');$('cloudInfo').textContent='Önce Supabase SQL kurulumunu çalıştır.';return}cloudWeeks=data||[];const select=$('weekSelect');select.innerHTML='<option value="">Hafta seç</option>'+cloudWeeks.map(w=>`<option value="${w.id}">${w.week_name} • ${(w.payload?.columns?.length||0)} kolon</option>`).join('');let chosen=state.cloudId&&cloudWeeks.find(w=>w.id===state.cloudId);if(!chosen&&state.weekKey)chosen=cloudWeeks.find(w=>w.week_key===state.weekKey);if(!chosen&&cloudWeeks.length)chosen=cloudWeeks[0];if(chosen)applyCloudWeek(chosen);updateDeleteWeekButton();$('cloudInfo').textContent=cloudWeeks.length?`${cloudWeeks.length} hafta kayıtlı • Anlık senkronizasyon açık`:'Henüz bulutta hafta yok. Excel yükle.'}
function applyCloudWeek(row){if(!row?.payload)return;isApplyingRemote=true;Object.assign(state,row.payload,{cloudId:row.id,cloudUpdatedAt:row.updated_at,weekKey:row.week_key,weekName:row.week_name,fileName:row.file_name});normalizeState();saveLocal();updateHeader();renderMatches();calculate();$('weekSelect').value=row.id;setSync('Güncel','online');setTimeout(()=>isApplyingRemote=false,0)}
function updateDeleteWeekButton(){const btn=$('deleteWeekBtn');if(!btn)return;btn.classList.toggle('hidden',!currentUser||!$('weekSelect').value)}
async function saveCloudNow(){if(!currentUser||!db||isApplyingRemote||!state.columns.length)return;setSync('Kaydediliyor','saving');const row={user_id:currentUser.id,week_key:state.weekKey||makeWeekKey(state),week_name:state.weekName||'Güncel Hafta',file_name:state.fileName||'',payload:safeStatePayload(),updated_at:new Date().toISOString()};const {data,error}=await db.from('karum_weeks').upsert(row,{onConflict:'user_id,week_key'}).select().single();if(error){console.error(error);setSync('Kayıt hatası','error');return}state.cloudId=data.id;state.cloudUpdatedAt=data.updated_at;saveLocal();setSync('Güncel','online');await loadCloudWeeks()}
function queueCloudSave(){if(!currentUser)return;clearTimeout(saveTimer);setSync('Kaydediliyor','saving');saveTimer=setTimeout(saveCloudNow,350)}
function subscribeRealtime(){unsubscribeRealtime();if(!currentUser||!db)return;realtimeChannel=db.channel('karum-weeks-'+currentUser.id).on('postgres_changes',{event:'*',schema:'public',table:'karum_weeks'},payload=>{if(payload.eventType==='DELETE'){loadCloudWeeks();return}const row=payload.new;if(!row||row.user_id!==currentUser.id)return;const localTime=new Date(state.cloudUpdatedAt||0).getTime(),remoteTime=new Date(row.updated_at||0).getTime();if(row.id===state.cloudId&&remoteTime>localTime+100)applyCloudWeek(row);else if(row.id!==state.cloudId)loadCloudWeeks()}).subscribe(status=>{if(status==='SUBSCRIBED')setSync('Anlık bağlı','online')})}
function unsubscribeRealtime(){if(realtimeChannel&&db)db.removeChannel(realtimeChannel);realtimeChannel=null}
$('fileInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{let imported;if(/\.csv$|\.txt$/i.test(f.name)){const rows=(await f.text()).split(/\r?\n/).map(line=>line.split(/[;,\t ]+/)),columns=parseRows(rows);if(!columns.length)throw new Error('15 sonuçtan oluşan kolon bulunamadı.');imported={matchNames:state.matchNames,matchLeagues:state.matchLeagues,matchDates:state.matchDates,matchTimes:state.matchTimes,results:Array(15).fill(''),columns,weekName:f.name.replace(/\.[^.]+$/,''),fileName:f.name};imported.weekKey=makeWeekKey(imported)}else{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellFormula:false,cellHTML:false});imported=parseWorkbook(wb,f.name)}Object.assign(state,imported,{cloudId:null,cloudUpdatedAt:null});normalizeState();saveLocal();updateHeader();renderMatches();calculate();if(currentUser)await saveCloudNow();else showAuth();alert(`${state.columns.length.toLocaleString('tr-TR')} kolon yüklendi.\n\nBu hafta buluta kaydedildiğinde telefon ve bilgisayar aynı seçimleri gösterecek.`)}catch(err){console.error(err);alert('Dosya yüklenemedi: '+err.message)}finally{e.target.value=''}});
$('weekSelect').onchange=()=>{const row=cloudWeeks.find(w=>w.id===$('weekSelect').value);if(row)applyCloudWeek(row);updateDeleteWeekButton()};
$('deleteWeekBtn').onclick=async()=>{const id=$('weekSelect').value,row=cloudWeeks.find(w=>w.id===id);if(!currentUser||!id||!row)return;const ok=confirm(`"${row.week_name}" haftasını kalıcı olarak silmek istiyor musun?\n\nBu işlem telefon ve bilgisayardaki ortak kaydı siler.`);if(!ok)return;setSync('Siliniyor','saving');const {error}=await db.from('karum_weeks').delete().eq('id',id).eq('user_id',currentUser.id);if(error){console.error(error);setSync('Silme hatası','error');alert('Hafta silinemedi: '+error.message);return}cloudWeeks=cloudWeeks.filter(w=>w.id!==id);if(state.cloudId===id){state.cloudId=null;state.cloudUpdatedAt=null;state.weekKey='';state.weekName='Güncel Hafta';state.fileName='';state.matchNames=Array.from({length:15},(_,i)=>`Takım ${i+1}A - Takım ${i+1}B`);state.matchLeagues=Array(15).fill('');state.matchDates=Array(15).fill('');state.matchTimes=Array(15).fill('');state.results=Array(15).fill('');state.columns=[];normalizeState();saveLocal();updateHeader();renderMatches();calculate()}await loadCloudWeeks();setSync('Anlık bağlı','online');alert('Hafta silindi.')} ;
document.querySelectorAll('.category-card').forEach(btn=>btn.onclick=()=>openCategory(btn.dataset.category));$('remainingMatchesBtn').onclick=openRemainingMatches;$('closeSheet').onclick=closeSurvivors;$('sheetBackdrop').onclick=closeSurvivors;
$('clearResults').onclick=()=>{state.results=Array(15).fill('');saveLocal();renderMatches();calculate();queueCloudSave()};
$('accountBtn').onclick=showAuth;$('closeAuth').onclick=closeAuth;$('authBackdrop').onclick=closeAuth;$('loginBtn').onclick=login;$('signupBtn').onclick=signup;$('logoutBtn').onclick=logout;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSurvivors();closeAuth()}});
loadLocal();normalizeState();updateHeader();renderMatches();calculate();initSupabase();setInterval(refreshMatchStatuses,30000);
window.addEventListener('load',()=>{const splash=$('splash');if(splash){setTimeout(()=>splash.classList.add('hide'),650);setTimeout(()=>splash.remove(),1150)}});
