const state={matchNames:[],results:Array(15).fill(''),columns:[]};
const $=id=>document.getElementById(id);
function normalize(v){v=String(v??'').trim().toUpperCase();return v==='1'||v==='2'||v==='X'?v:''}
function save(){localStorage.setItem('sporTotoState',JSON.stringify(state))}
function load(){try{const s=JSON.parse(localStorage.getItem('sporTotoState'));if(s&&Array.isArray(s.columns)){Object.assign(state,s);return}}catch(e){} Object.assign(state,window.INITIAL_DATA||{});save()}
function renderMatches(){const box=$('matches');box.innerHTML='';state.matchNames.forEach((name,i)=>{const d=document.createElement('div');d.className='match';d.innerHTML=`<div class="match-head"><span class="match-no">${i+1}</span><span class="match-name">${name||'Maç '+(i+1)}</span></div><div class="choices">${['1','X','2'].map(v=>`<button class="choice ${state.results[i]===v?'active':''}" data-i="${i}" data-v="${v}">${v}</button>`).join('')}</div>`;box.appendChild(d)});box.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,v=b.dataset.v;state.results[i]=state.results[i]===v?'':v;save();renderMatches();calculate()})}
function calculate(){let counts={15:0,14:0,13:0,12:0,11:0},perfect=[];const entered=state.results.filter(Boolean).length;for(let idx=0;idx<state.columns.length;idx++){const col=state.columns[idx];let wrong=0;for(let i=0;i<15;i++)if(state.results[i]&&col[i]!==state.results[i])wrong++;const score=15-wrong;if(score>=15){counts[15]++;perfect.push([idx+1,col])}else if(score===14)counts[14]++;else if(score===13)counts[13]++;else if(score===12)counts[12]++;else counts[11]++}
$('total').textContent=state.columns.length.toLocaleString('tr-TR');$('cost').textContent=(state.columns.length*10).toLocaleString('tr-TR')+' TL';$('s15').textContent=counts[15];$('s14').textContent=counts[14];$('s13').textContent=counts[13];$('s12').textContent=counts[12];$('s11').textContent=counts[11];$('remaining').textContent=15-entered;
const panel=$('survivorsPanel'), list=$('survivors');if(counts[15]<=10&&counts[15]>0){panel.classList.remove('hidden');$('survivorsTitle').textContent='15 Devam Eden Kolonlar';list.innerHTML=perfect.map(([n,c])=>`<div class="survivor">#${n} &nbsp; ${c.join(' ')}</div>`).join('')}else{panel.classList.add('hidden')}}
function parseRows(rows){const out=[];for(const row of rows){let vals=row.map(normalize);if(vals.length>=16&&!['1','X','2'].includes(vals[0]))vals=vals.slice(1,16);else vals=vals.slice(0,15);if(vals.length===15&&vals.every(Boolean))out.push(vals)}return out}
$('fileInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{let rows=[];if(/\.csv$|\.txt$/i.test(f.name)){const text=await f.text();rows=text.split(/\r?\n/).map(line=>line.split(/[;,\t ]+/))}else{if(!window.XLSX)throw new Error('Excel okuyucu yüklenemedi. İnternet bağlantısını kontrol et.');const data=await f.arrayBuffer();const wb=XLSX.read(data);let ws=wb.Sheets['Kolonlar']||wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});}
const cols=parseRows(rows);if(!cols.length)throw new Error('15 sonuçtan oluşan kolon bulunamadı.');state.columns=cols;state.results=Array(15).fill('');save();renderMatches();calculate();alert(cols.length+' kolon yüklendi.')}catch(err){alert(err.message)}});
$('clearResults').onclick=()=>{state.results=Array(15).fill('');save();renderMatches();calculate()};$('resetBtn').onclick=()=>{if(confirm('Uygulamadaki kayıtları ilk hâline döndürmek istiyor musun?')){localStorage.removeItem('sporTotoState');location.reload()}};
load();state.matchNames=(state.matchNames||[]).slice(0,15);while(state.matchNames.length<15)state.matchNames.push('Maç '+(state.matchNames.length+1));state.results=(state.results||[]).map(normalize).slice(0,15);while(state.results.length<15)state.results.push('');renderMatches();calculate();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});